image: registry.gitlab.com/edgardo.ibanez/ifn
stages:
  - prepare
  - test
  # - deploy

before_staging:
  stage: prepare
  tags:
    - staging
  only:
    - develop
  script:
    - echo "BEFORE_STAGING"
    - git fetch
    - git checkout staging
    - git reset --hard
    - git pull origin staging

linter:
  stage: test
  tags:
    - staging
  script:
    # Linter
    - echo "LINTER"
    - git stash
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard
    - git pull origin $CI_COMMIT_REF_NAME
    - pip install -r backend/requirements.txt
    - cp backend/ifn/local_settings.pipe.py backend/ifn/local_settings.py
    # Test
    - coverage3 run --source='.' backend/manage.py test
    - coverage3 report
    - coverage3 xml
  artifacts:
    reports:
      cobertura: coverage.xml
  after_script:
    - git fetch
    - git checkout staging
    - git reset --hard
    - git pull origin staging

# before_production:
#   stage: prepare
#   tags:
#     - production
#   only:
#     - master
#   script:
#     - cd /home/ubuntu/ifn
#     - git fetch
#     - git checkout master
#     - git pull origin master



# after_staging:
#   stage: deploy
#   tags:
#     - staging
#   only:
#     - develop
#   script:
#     - cd /home/gitlab-runner/ifn
#     - docker-compose exec -d web pip install -r requirements.txt
#     # DB sync
#     - docker-compose exec -d web python3.7 manage.py migrate
#     # Static sync
#     - docker-compose exec -d web python3.7 manage.py collectstatic --no-input
#     # Restart web server
#     - docker-compose exec -d web service apache2 restart

# after_production:
#   stage: deploy
#   tags:
#     - production
#   only:
#     - master
#   script:
#     - cd /home/ubuntu/ifn
#     - docker-compose exec -d web pip install -r requirements.txt
#     # DB sync
#     - docker-compose exec -d web python3.7 manage.py migrate
#     # Static sync
#     - docker-compose exec -d web python3.7 manage.py collectstatic --no-input
#     # Restart web server
#     - docker-compose exec -d web service apache2 restart
