version: '3'
services:
  web: # uwsgi
    container_name: app_web_inaturalist
    build:
      context: .
      dockerfile: Dockerfile.back
    image: inaturalist/ubuntu:v1b
    networks:
      - backend
    ports:
      - "0.0.0.0:${WEB_HTTPS_PORT}:443"
      - "0.0.0.0:${WEB_HTTP_DEV_PORT}:8000"
      - "8009:84" #  nginx proxy -> backend
      - "8005:8081" # backend = django
      - "80:80" # backend = django
    volumes:
      - ./:/app
      - ../bin:/usr/local/scripts
      - ../nginx:/nginx
      - ../static:/static
    environment:
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
      DJANGO_SECRET: ${DJANGO_SECRET}
      FRONT_URL: ${FRONT_URL}
      DRF_RECAPTCHA_SECRET_V3: ${DRF_RECAPTCHA_SECRET_V3}
      INAT_CLIENT_ID: ${INAT_CLIENT_ID}
      INAT_SECRET: ${INAT_SECRET}
      GCP_BQ_CREDS_JSON: ${GCP_BQ_CREDS_JSON} # Bigquery app_creds
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    # restart: always
    depends_on:
      - db
      - redis
    tty: true
  db:
    image: postgres
    container_name: postgres_inaturalist
    networks:
      - backend
    volumes:
      #- ./database:/var/lib/postgresql/data
      - ./bin:/usr/local/scripts
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    # restart: always
    ports:
      - "0.0.0.0:${POSTGRES_PORT}:5432"
    command:
      -c fsync=off
  redis:
    container_name: redis_inaturalist
    image: redis:latest
    # restart: always
    networks:
      - backend
    ports:
      - "6397:6379"
networks:
  backend:
      driver: bridge
